<template>
  <div class="setting">
    <div v-if="success" class="updated notice notice-success">
      Settings Saved
    </div>
    <div class="setting__wrap">
      <div class="setting__item">
        <label class="setting__label" for="use_imgix"> Enabled imgix CDN</label>
        <div class="setting__description">
          If you want to use imgix to generate and store your image size, you need first to
          <a rel="noopener noreferrer" href="https://dashboard.imgix.com/sign-up" target="_blank">create an account</a>
          on imgix
        </div>
        <toggle-button
          id="use_imgix"
          color="#5bd05b"
          :sync="true"
          :width="60"
          :height="25"
          :font-size="18"
          v-model="imgix"
          :labels="{ checked: 'on', unchecked: 'off' }"
        />
      </div>
      <div class="setting__item" v-if="imgix">
        <label class="setting__label" for="imgix_url">
          Imgix url
        </label>
        <div class="setting__description">
          p.ex: pictifly.imgix.net. <br />
          (Note: Your imgix url should point in your root path of WordPress.)
        </div>
        <input type="text" v-model="imgixUrl" id="imgix_url" name="imgix_url" placeholder="yourcompany.imgix.com" />
      </div>
      <div class="setting__item">
        <label class="setting__label" for="lazyload">
          Enabled LazyLoad
        </label>
        <toggle-button
          id="lazyload"
          :sync="true"
          color="#5bd05b"
          :width="60"
          :height="25"
          :font-size="18"
          v-model="lazyload"
          :labels="{ checked: 'on', unchecked: 'off' }"
        />
      </div>
      <div class="setting__item">
        <label class="setting__label" for="pictifly_quality">
          Pictifly image quality
        </label>
        <div class="setting__description">
          Set the quality of the images generated by Pictifly here. Pictifly uses imagick to compress your images. This
          compression algorithm creates worse results than compression via the browser. If you are planning to use the compression
          tool we recommend leaving this setting at 100%.
          <small>Note: if you change this setting all your image as to be regenerate</small>
        </div>
        <input
          type="number"
          v-model="pictiflyQuality"
          min="0"
          max="100"
          @input="validatePictiflyQuality"
          id="pictifly_quality"
          name="pictifly_quality"
        />
      </div>
      <div class="setting__item">
        <label class="setting__label" for="compression_quality">
          Compression quality
        </label>
        <div class="setting__description">
          Set the compression quality here, the lower the quality, the lighter the image will be. We recommend setting this to 75
          <small>Note: if you change this setting you need to rerun compression tool</small>
        </div>
        <input
          type="number"
          @input="validateCompressionQuality"
          v-model="compressionQuality"
          min="0"
          max="95"
          id="compression_quality"
          name="compression_quality"
        />
      </div>
      <ui-button :loading="isRunning" @click="save" color="white" outline>Save</ui-button>
      <ConfirmationModal
        v-if="confirmation !== false"
        :title="confirmation.title"
        :confirmText="confirmation.confirmText"
        confirmColor="green"
        @confirm="confirmation.callback()"
        @close="closeConfirmation"
      >
        <div
          v-for="(content, idx) in confirmation.content"
          :key="'confirmationcontent' + idx"
          class="confirmation__content__item"
        >
          <div><svgicon icon="alert-triangle"></svgicon>{{ " " + content.text }}</div>
          <small v-if="content.small">{{ content.small }}</small>
        </div>
      </ConfirmationModal>
    </div>
  </div>
</template>
<script>
import ConfirmationModal from "../components/ConfirmationModal.vue";
import { ToggleButton } from "vue-js-toggle-button";
const $ = jQuery;

export default {
  components: {
    ToggleButton,
    ConfirmationModal,
  },
  data() {
    const { nonce, ajaxUrl } = this.$store.state.pictifly;
    return {
      success: false,
      confirmation: false,
      isRunning: false,
      imgix: false,
      imgixUrl: "",
      lazyload: false,
      compressionQuality: 10,
      pictiflyQuality: 100,
      nonce: nonce,
      ajaxUrl: ajaxUrl,
    };
  },
  created() {
    this.setOptions();
  },
  methods: {
    setOptions() {
      const { options } = this.$store.state.pictifly;
      this.imgix = options && options.imgix;
      this.imgixUrl = options && options.imgix_url;
      this.lazyload = options && options.lazyload;
      this.compressionQuality = options && options.compression_quality;
      this.pictiflyQuality = options && options.pictifly_quality;
    },
    validatePictiflyQuality(e) {
      const val = parseInt(e.target.value);
      if (val > 100) {
        this.pictiflyQuality = 100;
      } else if (val < 0) {
        this.pictiflyQuality = 0;
      } else {
        this.pictiflyQuality = val;
      }
    },
    validateCompressionQuality(e) {
      const val = parseInt(e.target.value);
      if (val > 95) {
        this.compressionQuality = 90;
      } else if (val < 0) {
        this.compressionQuality = 0;
      } else {
        this.compressionQuality = val;
      }
    },
    save() {
      const content = [];
      const { options } = this.$store.state.pictifly;
      if (options.compression_quality !== this.compressionQuality) {
        content.push({
          text: "Are you sure you want to change the compression quality?",
          small: "This means that all compressed images will be deleted, you will have to regenerate it.",
        });
      }
      if (options.pictifly_quality !== this.pictiflyQuality) {
        content.push({
          text: "Are you sure you want to change the quality of the pictifly images?",
          small:
            "Be careful, this means that all the images on your site will have to be regenerated. This action can temporarily slow down your site and consume a lot of server resources.",
        });
      }
      if (content.length > 0) {
        this.confirmation = {
          title: "Are you sure you want to save these settings?",
          confirmText: "Confirm",
          content: content,
          callback: this.saveSettings,
        };
      } else {
        this.saveSettings();
      }
    },
    saveSettings() {
      this.confirmation = false;
      this.isRunning = true;
      const data = {
        action: "pf_save_plugin_settings",
        nonce: this.nonce,
        imgix: this.imgix,
        imgix_url: this.imgixUrl,
        lazyload: this.lazyload,
        compression_quality: this.compressionQuality,
        pictifly_quality: this.pictiflyQuality,
      };
      $.ajax({
        type: "post",
        url: this.ajaxUrl,
        data: data,
        success: response => {
          this.isRunning = false;
          this.success = true;
          this.$store.commit("saveOptions", response.data.options);
          this.setOptions();
        },
      });
    },
    closeConfirmation() {
      this.confirmation = false;
    },
  },
};
</script>
<style lang="scss" scoped>
.setting {
  text-align: left;
  &__wrap {
    width: 90%;
    margin: auto;
    max-width: 800px;
  }
  &__item {
    margin-bottom: 25px;
    input {
      padding: 4px 10px;
      &[type="text"] {
        max-width: 300px;
        width: 90%;
      }
    }
  }
  &__label {
    font-size: 20px;
    font-weight: bold;
    margin-bottom: 10px;
    display: block;
    cursor: default;
  }
  &__description {
    font-size: 16px;
    margin-bottom: 10px;
    a {
      color: $primary;
    }
    small {
      font-size: 14px;
      opacity: 0.8;
      display: block;
      margin-top: 5px;
    }
  }
  .confirmation__content__item {
    div {
      color: $red;
    }
    + .confirmation__content__item {
      margin-top: 20px;
    }
  }
  .notice {
    color: $background;
    margin-bottom: 20px;
    font-size: 16px;
    padding: 10px;
  }
}
</style>
