<template>
  <div class="tool">
    <ConfirmationModal
      v-if="confirmation !== false"
      :title="confirmation.title"
      :confirmText="confirmation.action"
      @confirm="confirmation.callback(confirmation)"
      @close="closeConfirmation"
    >
      Are you sure your want {{ confirmation.title }} ?
      <small>This action can not be undone ! {{ confirmation.tip }}</small>
    </ConfirmationModal>

    <div class="tool__item" v-for="(tool, idx) in tools" :key="'tool' + idx">
      <div class="tool__content">
        <h3 class="tool__title">{{ tool.title }}</h3>
        <p class="tool__description">
          {{ tool.description }}
          <small v-if="tool.tip">{{ tool.tip }}</small>
        </p>
      </div>
      <div class="tool__actions">
        <ui-button v-if="!tool.done" color="white" @click="toolCallback(tool)" outline size="s" :loading="tool.loading">{{
          tool.action
        }}</ui-button>
        <span v-else><svgicon icon="check-circle" />Done</span>
      </div>
    </div>
  </div>
</template>
<script>
import ConfirmationModal from "../components/ConfirmationModal.vue";
const $ = jQuery;
export default {
  components: { ConfirmationModal },
  data() {
    const { ajaxUrl, nonce } = this.$store.state.pictifly;
    return {
      nonce: nonce,
      ajaxUrl: ajaxUrl,
      confirmation: false,
      tools: [
        {
          title: "Delete all compressed images",
          description: "Remove all compressed image generated by Pictfifly",
          tip: null,
          action: "Delete",
          callback: this.deleteAllCompressed,
          confirmation: true,
          done: false,
          loading: false,
        },
        {
          title: "Delete all Pictifly images",
          description: "Remove all compressed image generated by Pictfifly",
          tip:
            "Be careful, this means that all the images on your site will have to be regenerated. This action can temporarily slow down your site and consume a lot of server resources.",
          action: "Delete",
          callback: this.deleteAllImages,
          confirmation: true,
          done: false,
          loading: false,
        },
        {
          title: "Remove old pictifly data",
          description:
            "Before version 0.4 Pictifly added information about the generated images to the database. This data is no longer used and is therefore not required in your database.",
          tip: false,
          action: "Remove",
          callback: this.deleteOldData,
          confirmation: false,
          done: false,
          loading: false,
        },
      ],
    };
  },
  methods: {
    toolCallback(tool) {
      if (tool.confirmation) {
        this.toolConfirmation(tool);
      } else {
        tool.callback(tool);
      }
    },
    closeConfirmation() {
      this.confirmation = false;
    },
    toolConfirmation(tool) {
      this.confirmation = tool;
    },
    deleteAllCompressed(tool) {
      this.confirmation = false;
      tool.loading = true;
      const data = {
        action: "pf_ajax_delete_all_compressed",
        nonce: this.nonce,
      };
      $.ajax({
        type: "post",
        url: this.ajaxUrl,
        data: data,
        success: () => {
          tool.done = true;
        },
      });
    },
    deleteAllImages(tool) {
      this.confirmation = false;
      tool.loading = true;
      const data = {
        action: "pf_ajax_delete_all_image",
        nonce: this.nonce,
      };
      $.ajax({
        type: "post",
        url: this.ajaxUrl,
        data: data,
        success: () => {
          tool.done = true;
        },
      });
    },
    deleteOldData(tool) {
      tool.loading = true;
      const data = {
        action: "pf_ajax_delete_all_past_data",
        nonce: this.nonce,
      };

      $.ajax({
        type: "post",
        url: this.ajaxUrl,
        data: data,
        success: () => {
          tool.done = true;
        },
      });
    },
  },
};
</script>
<style lang="scss" scoped>
.tool {
  max-width: 600px;
  margin: auto;
  text-align: left;
  &__item {
    display: flex;
    align-items: center;
    & + & {
      border-top: 1px solid rgba($white, 0.3);
    }
  }
  &__content {
    padding-right: 20px;
    flex-grow: 1;
  }
  &__title {
    font-size: 22px;
    color: white;
  }
  &__description {
    font-size: 16px;
    small {
      display: block;
      opacity: 0.5;
    }
  }
  &__actions {
    text-align: right;
    min-width: 100px;
    span {
      display: flex;
      align-items: center;
      justify-content: flex-end;
      text-align: right;
      color: $green-flash;
      ::v-deep svg {
        margin-right: 5px;
      }
    }
  }
}
</style>
